# Generated by Django 5.2.8 on 2025-11-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vehiculo', models.CharField(max_length=100, verbose_name='Nombre del Vehículo')),
                ('tipo_vehiculo', models.CharField(choices=[('camioneta', 'Camioneta'), ('tanque', 'Tanque'), ('moto', 'Moto'), ('helicoptero', 'Helicóptero'), ('avion', 'Avión'), ('ambulancia', 'Ambulancia')], max_length=50, verbose_name='Tipo de Vehículo')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa del Vehículo')),
                ('imagen_vehiculo', models.ImageField(blank=True, null=True, upload_to='imagenes_vehiculos/', verbose_name='Imagen del Vehículo')),
                ('nombre_responsable', models.CharField(max_length=100, verbose_name='Nombre de quien sube')),
                ('rango_responsable', models.CharField(choices=[('soldado', 'Soldado Profesional'), ('cabo', 'Cabo'), ('suboficial', 'Suboficial'), ('sargento', 'Sargento'), ('tecnico', 'Técnico de Mantenimiento'), ('supervisor', 'Supervisor'), ('jefe', 'Jefe de Unidad'), ('comandante', 'Comandante')], max_length=20, verbose_name='Rango de quien sube')),
                ('observacion_mantenimiento', models.TextField(blank=True, null=True, verbose_name='Observación de Mantenimiento')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
